# ╭─────────────────────────────────ImplementationGuide-hl7.fhir.uv.RE.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.cl.CoreCH
canonical: http://core.hl7chile.cl
version: 0.9 (Ballot Pendiente)
name: CoreCL

title: Guía de Implementación Core-CL
status: draft
date: 2021-12
publisher: HL7 Chile / Ministerio de Salud, Chile  
contact:
  - name: Pablo Pizzaro
    telecom:
      - system: email
        value: ppizarro.delgado@minsal.cl
description: Guía de Implementación para los perfiles Core que se van a requerir a nivel de desarrollo Nacional
jurisdiction: urn:iso:std:iso:3166#CL "Chile"
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: ci-build



# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

menu:
  Inicio: index.html
  Balloting: 
    Balotaje: Balloting.html
    Revisores: Balloting-Validadores.html
  Objetivos: Alcances-Objetivos.html
  Generalidades: Aspectos-Generales.html
  Operaciones: Consolidado-Operaciones.html
  Artefactos:
   Perfiles: Perfiles.html
   Extensiones: Extensiones.html
   Valuesets: Set-De-Validacion-ValueSets.html
  Perfiles: 
    Paciente: StructureDefinition-CorePacienteCl.html
    Prestador: StructureDefinition-CorePrestadorCl.html
    Especialidad Prestador: StructureDefinition-CoreEspecialidadCl.html
    Organización: StructureDefinition-CoreOrganizacionCl.html
    Medicamento: StructureDefinition-CoreMedicamentoCl.html
    Localización: StructureDefinition-CoreLocalizacionCl.html
    Bundle: StructureDefinition-RecetaBundleCl.html
  Ejemplos: Set-Ejemplos.html
  Descargas: Todas-Descargas.html
 
  
  
  #Historia: http://hl7.org/fhir/us/example/history.html  
  

#Inicio: index.html
  #Tabla de Contenidos: toc.html
  #Resumen de Artefactos: artifacts.html
  #Otros Recursos:
  #  "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
